#include <stdio.h>
#include <stdlib.h>
#include <time.h>
/*
The array size has been set to a fixed maximum.
This means that in most cases, the array will have many trailing empty indices.
However, when QuickSort() and BubbleSort() are called, only the filled slots will be passed
This isn't the most memory-efficient way of doing things, but it should be sufficient for the purpose of this assignment.
*/

#define MAX_SIZE 100000 // max array size of one hundred thousand
int numbers[2][MAX_SIZE];

// Function to swap values for sorting purposes
void swap(int *a, int *b) {
    int temp = *a;
    *a = *b;
    *b = temp;
}

// Partition function for Quick Sort
int Partition(int arr[], int lowIndex, int highIndex) {
    int pivot = arr[highIndex];
    int i = lowIndex - 1;

    for (int j = lowIndex; j < highIndex; j++) {
        if (arr[j] < pivot) {
            i++;
            swap(&arr[i], &arr[j]);
        }
    }
    swap(&arr[i + 1], &arr[highIndex]);
    return i + 1;
}

// QuickSort function (I melted my brain trying to make this work)
void QuickSort(int arr[], int lowIndex, int highIndex) {
    if (lowIndex < highIndex) {
        int partitionIndex = Partition(arr, lowIndex, highIndex);
        QuickSort(arr, lowIndex, partitionIndex - 1);
        QuickSort(arr, partitionIndex + 1, highIndex);
    }
}

// BubbleSort function
void BubbleSort(int arr[], int length) {
    for (int i = 0; i < length - 1; i++) {
        for (int j = 0; j < length - i - 1; j++) {
            if (arr[j] > arr[j + 1]) {
                swap(&arr[j], &arr[j + 1]);
            }
        }
    }
}

// Function to fill remaining array indices with random numbers
void fillWithRandomNumbers(int arr[], int start, int length, int max) {
    for (int i = start; i < length; i++) {
        arr[i] = rand() % (max + 1); // the size of the numbers generated by rand() has been capped because it would be insane and needless to generate extremly large numbers
    }
}

// Function to display the array
void printArray(int arr[], int length) {
    for (int i = 0; i < length; i++) {
        printf("%6d", arr[i]); // prints the elemnts in a field size minimum 6 spots
    }
    printf("\n");
}

int main() {
    int n, m;
    char command;
    int initialized = 0;

    srand(time(NULL));

    do {
        if (!initialized || command == 'N') {
            // Input for n and m
            printf("Enter the number of numbers (n): ");
            scanf("%d", &n);
            printf("Enter the array length (m): ");
            scanf("%d", &m);

            // Validate n and m 
            if (n > m || n % 2 != 0 || m % 2 != 0) {
                printf("Error: m must be >= n, and both n and m must be even.\n");
                continue;
            }

            // Prompt for numbers and fill first row
            printf("Enter %d numbers:\n", n);
            int i;
            for (i = 0; i < n; i++) {
                if (scanf("%d", &numbers[0][i]) != 1) {
                    printf("Invalid input, filling with random numbers.\n");
                    break;
                }
            }

            // If less than n numbers entered, fill with random numbers
            if (i < n) {
                fillWithRandomNumbers(numbers[0], i, m, 100000);
            } else {
                fillWithRandomNumbers(numbers[0], n, m, 100000);
            }

            initialized = 1;
        }

        // Copy unsorted numbers to the second row for sorting
        for (int i = 0; i < m; i++) {
            numbers[1][i] = numbers[0][i];
        }

        // Choose sorting algorithm
        int choice;
        printf("Choose a sorting algorithm: (0) Quick Sort, (1) Bubble Sort\n");
        scanf("%d", &choice);

        // Measure sorting time
        time_t time1 = time(NULL);

        if (choice == 0) {
            QuickSort(numbers[1], 0, m - 1);
        } else if (choice == 1) {
            BubbleSort(numbers[1], m);
        } else {
            printf("Invalid choice.\n");
            continue;
        }

        time_t time2 = time(NULL);
        time_t deltaTime = time2 - time1;

        // Display results
        printf("Raw Array:\n");
        printArray(numbers[0], m);

        printf("Sorted Array:\n");
        printArray(numbers[1], m);

        printf("Sorting Duration (sec): %ld\n", deltaTime);

        // Command options
        printf("\nEnter a command:\n");
        printf("(R) Re-generate different random numbers and choose a different sorting algorithm.\n");
        printf("(N) Enter new values for n and m, and enter new n numbers.\n");
        printf("(S) Use a different sorting algorithm to sort the same array.\n");
        printf("(Q) Quit.\n");
        printf("Your choice: ");
        scanf(" %c", &command);

        // Handle command actions
        if (command == 'R' || command == 'r') {
            fillWithRandomNumbers(numbers[0], n, m, 100000);
        } else if (command == 'N' || command == 'n') {
            initialized = 0;
        } else if (command == 'S' || command == 's') {
            continue; // Sorting the same array with a different algorithm
        } else if (command == 'Q' || command == 'q') {
            printf("Exiting program.\n");
            break;
        } else {
            printf("Invalid command. Exiting program.\n");
            break;
        }

    } while (1);

    return 0;
}
